---
apiVersion: v1
kind: Namespace
metadata:
  name: tools

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: tools
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-credentials
  namespace: tools
data:
  JENKINS_USER: d3BfdXNlcg== #base64 encoded, to be replaced in terraform file
  JENKINS_PASS: cGFzc3dvcmQ= #base64 encoded, to be replaced in terraform file


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: jenkins-pv
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
      containers:
      - name: jenkins
        image: alibek17/jenkins:1.2
        env:
        - name: JENKINS_USER
          valueFrom:
            secretKeyRef:
              name: jenkins-credentials
              key: JENKINS_USER
        - name: JENKINS_PASS
          valueFrom:
            secretKeyRef:
              name: jenkins-credentials
              key: JENKINS_PASS
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - name: jenkins-pv
          mountPath: /var/jenkins_home

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: tools
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: jenkins
  type: NodePort